# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormAdd(object):
    def setupUi(self, FormAdd):
        FormAdd.setObjectName("FormAdd")
        FormAdd.resize(400, 213)
        FormAdd.setMinimumSize(QtCore.QSize(400, 213))
        FormAdd.setMaximumSize(QtCore.QSize(400, 213))
        self.gridLayout_2 = QtWidgets.QGridLayout(FormAdd)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(FormAdd)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditAddress = QtWidgets.QLineEdit(FormAdd)
        self.lineEditAddress.setObjectName("lineEditAddress")
        self.gridLayout.addWidget(self.lineEditAddress, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(FormAdd)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBoxPort = QtWidgets.QSpinBox(FormAdd)
        self.spinBoxPort.setMinimum(1)
        self.spinBoxPort.setMaximum(65535)
        self.spinBoxPort.setProperty("value", 22)
        self.spinBoxPort.setObjectName("spinBoxPort")
        self.gridLayout.addWidget(self.spinBoxPort, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(FormAdd)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEditUserName = QtWidgets.QLineEdit(FormAdd)
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.gridLayout.addWidget(self.lineEditUserName, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(FormAdd)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEditPassword = QtWidgets.QLineEdit(FormAdd)
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.gridLayout.addWidget(self.lineEditPassword, 3, 1, 1, 1)
        self.pushButtonTest = QtWidgets.QPushButton(FormAdd)
        self.pushButtonTest.setObjectName("pushButtonTest")
        self.gridLayout.addWidget(self.pushButtonTest, 4, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(293, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        self.pushButtonAdd = QtWidgets.QPushButton(FormAdd)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.gridLayout_2.addWidget(self.pushButtonAdd, 2, 1, 1, 1)

        self.retranslateUi(FormAdd)
        QtCore.QMetaObject.connectSlotsByName(FormAdd)

    def retranslateUi(self, FormAdd):
        _translate = QtCore.QCoreApplication.translate
        FormAdd.setWindowTitle(_translate("FormAdd", "Add Connection"))
        self.label.setText(_translate("FormAdd", "Address"))
        self.lineEditAddress.setText(_translate("FormAdd", "localhost"))
        self.label_2.setText(_translate("FormAdd", "Port"))
        self.label_3.setText(_translate("FormAdd", "Username"))
        self.lineEditUserName.setText(_translate("FormAdd", "niaei"))
        self.label_4.setText(_translate("FormAdd", "Password"))
        self.lineEditPassword.setText(_translate("FormAdd", "landofcanaan"))
        self.pushButtonTest.setText(_translate("FormAdd", "Test"))
        self.pushButtonAdd.setText(_translate("FormAdd", "Add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormAdd = QtWidgets.QWidget()
    ui = Ui_FormAdd()
    ui.setupUi(FormAdd)
    FormAdd.show()
    sys.exit(app.exec_())
