# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'apt.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormApt(object):
    def setupUi(self, FormApt):
        FormApt.setObjectName("FormApt")
        FormApt.resize(543, 582)
        self.gridLayout = QtWidgets.QGridLayout(FormApt)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(FormApt)
        self.label.setMinimumSize(QtCore.QSize(58, 18))
        self.label.setMaximumSize(QtCore.QSize(58, 18))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditSearch = QtWidgets.QLineEdit(FormApt)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.gridLayout.addWidget(self.lineEditSearch, 0, 1, 1, 4)
        self.treeWidget = QtWidgets.QTreeWidget(FormApt)
        self.treeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.treeWidget.setObjectName("treeWidget")
        self.gridLayout.addWidget(self.treeWidget, 1, 0, 1, 5)
        spacerItem = QtWidgets.QSpacerItem(193, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 2)
        self.pushButtonPrevious = QtWidgets.QPushButton(FormApt)
        self.pushButtonPrevious.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButtonPrevious.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButtonPrevious.setObjectName("pushButtonPrevious")
        self.gridLayout.addWidget(self.pushButtonPrevious, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(FormApt)
        self.label_2.setMinimumSize(QtCore.QSize(151, 0))
        self.label_2.setMaximumSize(QtCore.QSize(151, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 3, 1, 1)
        self.pushButtonNext = QtWidgets.QPushButton(FormApt)
        self.pushButtonNext.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButtonNext.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.gridLayout.addWidget(self.pushButtonNext, 2, 4, 1, 1)

        self.retranslateUi(FormApt)
        QtCore.QMetaObject.connectSlotsByName(FormApt)

    def retranslateUi(self, FormApt):
        _translate = QtCore.QCoreApplication.translate
        FormApt.setWindowTitle(_translate("FormApt", "Apt"))
        self.label.setText(_translate("FormApt", "Search"))
        self.treeWidget.headerItem().setText(0, _translate("FormApt", "Host"))
        self.treeWidget.headerItem().setText(1, _translate("FormApt", "Repo"))
        self.treeWidget.headerItem().setText(2, _translate("FormApt", "Version"))
        self.treeWidget.headerItem().setText(3, _translate("FormApt", "Arch"))
        self.treeWidget.headerItem().setText(4, _translate("FormApt", "Tags"))
        self.pushButtonPrevious.setText(_translate("FormApt", "Previous"))
        self.label_2.setText(_translate("FormApt", "TextLabel"))
        self.pushButtonNext.setText(_translate("FormApt", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormApt = QtWidgets.QWidget()
    ui = Ui_FormApt()
    ui.setupUi(FormApt)
    FormApt.show()
    sys.exit(app.exec_())
