# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conf.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormConfig(object):
    def setupUi(self, FormConfig):
        FormConfig.setObjectName("FormConfig")
        FormConfig.resize(681, 624)
        self.gridLayout_2 = QtWidgets.QGridLayout(FormConfig)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(718, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.pushButtonSave = QtWidgets.QPushButton(FormConfig)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.gridLayout_2.addWidget(self.pushButtonSave, 2, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(318, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 2)
        self.pushButtonOpen = QtWidgets.QPushButton(FormConfig)
        self.pushButtonOpen.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButtonOpen.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButtonOpen.setObjectName("pushButtonOpen")
        self.gridLayout.addWidget(self.pushButtonOpen, 3, 2, 1, 1)
        self.lineEdiPath = QtWidgets.QLineEdit(FormConfig)
        self.lineEdiPath.setObjectName("lineEdiPath")
        self.gridLayout.addWidget(self.lineEdiPath, 1, 1, 1, 2)
        self.label = QtWidgets.QLabel(FormConfig)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBoxLoad = QtWidgets.QComboBox(FormConfig)
        self.comboBoxLoad.setObjectName("comboBoxLoad")
        self.comboBoxLoad.addItem("")
        self.comboBoxLoad.addItem("")
        self.comboBoxLoad.addItem("")
        self.gridLayout.addWidget(self.comboBoxLoad, 0, 1, 1, 2)
        self.comboBoxKind = QtWidgets.QComboBox(FormConfig)
        self.comboBoxKind.setObjectName("comboBoxKind")
        self.comboBoxKind.addItem("")
        self.comboBoxKind.addItem("")
        self.gridLayout.addWidget(self.comboBoxKind, 2, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(FormConfig)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(FormConfig)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.plainTextEditConfig = QtWidgets.QPlainTextEdit(FormConfig)
        self.plainTextEditConfig.setObjectName("plainTextEditConfig")
        self.gridLayout_2.addWidget(self.plainTextEditConfig, 1, 0, 1, 2)

        self.retranslateUi(FormConfig)
        QtCore.QMetaObject.connectSlotsByName(FormConfig)

    def retranslateUi(self, FormConfig):
        _translate = QtCore.QCoreApplication.translate
        FormConfig.setWindowTitle(_translate("FormConfig", "Configuration"))
        self.pushButtonSave.setText(_translate("FormConfig", "Save"))
        self.pushButtonOpen.setText(_translate("FormConfig", "Open"))
        self.label.setText(_translate("FormConfig", "Load"))
        self.comboBoxLoad.setItemText(0, _translate("FormConfig", "---"))
        self.comboBoxLoad.setItemText(1, _translate("FormConfig", "Samba"))
        self.comboBoxLoad.setItemText(2, _translate("FormConfig", "Kerberos"))
        self.comboBoxKind.setItemText(0, _translate("FormConfig", "Raw"))
        self.comboBoxKind.setItemText(1, _translate("FormConfig", "Conf"))
        self.label_2.setText(_translate("FormConfig", "Path"))
        self.label_3.setText(_translate("FormConfig", "Type"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormConfig = QtWidgets.QWidget()
    ui = Ui_FormConfig()
    ui.setupUi(FormConfig)
    FormConfig.show()
    sys.exit(app.exec_())
