# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pack_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormPackageInfo(object):
    def setupUi(self, FormPackageInfo):
        FormPackageInfo.setObjectName("FormPackageInfo")
        FormPackageInfo.resize(650, 657)
        self.gridLayout_3 = QtWidgets.QGridLayout(FormPackageInfo)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(FormPackageInfo)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidgetInformation = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidgetInformation.setObjectName("tableWidgetInformation")
        self.tableWidgetInformation.setColumnCount(2)
        self.tableWidgetInformation.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInformation.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInformation.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.tableWidgetInformation, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(FormPackageInfo)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plainTextEditDescription = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEditDescription.setReadOnly(True)
        self.plainTextEditDescription.setObjectName("plainTextEditDescription")
        self.gridLayout_2.addWidget(self.plainTextEditDescription, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(543, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 1)
        self.pushButtonReload = QtWidgets.QPushButton(FormPackageInfo)
        self.pushButtonReload.setObjectName("pushButtonReload")
        self.gridLayout_3.addWidget(self.pushButtonReload, 2, 1, 1, 1)

        self.retranslateUi(FormPackageInfo)
        QtCore.QMetaObject.connectSlotsByName(FormPackageInfo)

    def retranslateUi(self, FormPackageInfo):
        _translate = QtCore.QCoreApplication.translate
        FormPackageInfo.setWindowTitle(_translate("FormPackageInfo", "Pckage Information"))
        self.groupBox.setTitle(_translate("FormPackageInfo", "Information"))
        item = self.tableWidgetInformation.horizontalHeaderItem(0)
        item.setText(_translate("FormPackageInfo", "Key"))
        item = self.tableWidgetInformation.horizontalHeaderItem(1)
        item.setText(_translate("FormPackageInfo", "Value"))
        self.groupBox_2.setTitle(_translate("FormPackageInfo", "Description"))
        self.pushButtonReload.setText(_translate("FormPackageInfo", "Reload"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormPackageInfo = QtWidgets.QWidget()
    ui = Ui_FormPackageInfo()
    ui.setupUi(FormPackageInfo)
    FormPackageInfo.show()
    sys.exit(app.exec_())
