# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'services.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormServices(object):
    def setupUi(self, FormServices):
        FormServices.setObjectName("FormServices")
        FormServices.resize(565, 672)
        self.gridLayout = QtWidgets.QGridLayout(FormServices)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(FormServices)
        self.label.setMinimumSize(QtCore.QSize(58, 18))
        self.label.setMaximumSize(QtCore.QSize(58, 18))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEditSearch = QtWidgets.QLineEdit(FormServices)
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.gridLayout.addWidget(self.lineEditSearch, 0, 1, 1, 1)
        self.treeWidget = QtWidgets.QTreeWidget(FormServices)
        self.treeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.treeWidget.setObjectName("treeWidget")
        self.gridLayout.addWidget(self.treeWidget, 1, 0, 1, 2)

        self.retranslateUi(FormServices)
        QtCore.QMetaObject.connectSlotsByName(FormServices)

    def retranslateUi(self, FormServices):
        _translate = QtCore.QCoreApplication.translate
        FormServices.setWindowTitle(_translate("FormServices", "Services"))
        self.label.setText(_translate("FormServices", "Search"))
        self.treeWidget.headerItem().setText(0, _translate("FormServices", "Host"))
        self.treeWidget.headerItem().setText(1, _translate("FormServices", "Load"))
        self.treeWidget.headerItem().setText(2, _translate("FormServices", "Active"))
        self.treeWidget.headerItem().setText(3, _translate("FormServices", "Substate"))
        self.treeWidget.headerItem().setText(4, _translate("FormServices", "Description"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormServices = QtWidgets.QWidget()
    ui = Ui_FormServices()
    ui.setupUi(FormServices)
    FormServices.show()
    sys.exit(app.exec_())
